name: digital14
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  adaptive_components: ^0.0.3
  adaptive_navigation: ^0.0.5
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dynamic_color: ^1.1.2
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  go_router: ^3.0.1
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  material_color_utilities: ^0.1.4
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
