// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlYG9_6tPBFAD5Z-RcM0pXQzjc0c1OZIM',
    appId: '1:748001249259:web:40ef7de1d03f5e9e6c3bae',
    messagingSenderId: '748001249259',
    projectId: 'digital14-bfc7e',
    authDomain: 'digital14-bfc7e.firebaseapp.com',
    storageBucket: 'digital14-bfc7e.appspot.com',
    measurementId: 'G-MRMGSRBTJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3XQOJeIBKryjYjYNkp6PMQuFprVlgYQ',
    appId: '1:748001249259:android:8e94977b8e17d2466c3bae',
    messagingSenderId: '748001249259',
    projectId: 'digital14-bfc7e',
    storageBucket: 'digital14-bfc7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBNDmRQh113Rf6rhZfoBFqLETDWiIcD18',
    appId: '1:748001249259:ios:957bb6ab796c0a626c3bae',
    messagingSenderId: '748001249259',
    projectId: 'digital14-bfc7e',
    storageBucket: 'digital14-bfc7e.appspot.com',
    iosClientId:
        '748001249259-0ta0shn0al2l4j4s4eh7etkeu5vdunqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.digital14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBNDmRQh113Rf6rhZfoBFqLETDWiIcD18',
    appId: '1:748001249259:ios:957bb6ab796c0a626c3bae',
    messagingSenderId: '748001249259',
    projectId: 'digital14-bfc7e',
    storageBucket: 'digital14-bfc7e.appspot.com',
    iosClientId:
        '748001249259-0ta0shn0al2l4j4s4eh7etkeu5vdunqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.digital14',
  );
}
